import { readFile, writeFile } from 'node:fs/promises';
import vm from 'node:vm';

// Source text stays readable and editable without a Markdown dependency.
// Supported syntax: headings, paragraphs, fenced code and HTTPS links.
const esc = s => s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function inline(s) {
  return esc(s).replace(/\[([^\]]+)\]\((https:\/\/[^\s)]+)\)/g,
    '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');
}
function blocks(s) {
  return s.trim().split(/(```[^\n]*\n[\s\S]*?\n```)/g).filter(Boolean).map(part => {
    if (part.startsWith('```')) {
      const code = part.replace(/^```[^\n]*\n/, '').replace(/\n```$/, '');
      return `<pre tabindex="0" aria-label="Пример кода"><code>${esc(code)}</code></pre>`;
    }
    return part.trim().split(/\n\s*\n/).filter(Boolean).map(p => `<p>${inline(p.replace(/\n/g, ' '))}</p>`).join('\n');
  }).join('\n');
}
const root = new URL('./', import.meta.url);
const source = await readFile(new URL('lessons-content.md', root), 'utf8');
const sandbox = { window: {} };
vm.runInNewContext(await readFile(new URL('tickets.js', root), 'utf8'), sandbox);
const tickets = sandbox.window.TICKETS;
const chapters = [...source.matchAll(/^# (\d+)\. (.+)\n([\s\S]*?)(?=^# \d+\. |$(?![\s\S]))/gm)];
const lessons = {};
for (const [, id, title, body] of chapters) {
  if (lessons[id]) throw new Error(`Duplicate lesson ${id}`);
  const sections = [...body.matchAll(/^## (.+)\n([\s\S]*?)(?=^## |$(?![\s\S]))/gm)]
    .map(([, heading, text]) => ({ heading, html: blocks(text) }));
  if (sections.length < 5 || sections.at(-1).heading !== 'Ответ к упражнению') throw new Error(`Incomplete lesson ${id}`);
  if ((body.match(/^```/gm) || []).length % 2) throw new Error(`Unclosed code fence ${id}`);
  const words = body.split(/\s+/).filter(Boolean).length;
  if (words < 250) throw new Error(`Lesson ${id} too short: ${words}`);
  lessons[id] = { title, words, sections };
}
if (chapters.length !== tickets.length || tickets.some(t => !lessons[t.n])) throw new Error('Ticket/lesson coverage mismatch');
const output = '// Generated by node build-lessons.mjs from lessons-content.md.\nwindow.LESSONS = '
  + JSON.stringify(lessons, null, 2).replace(/</g, '\\u003c') + ';\n';
const target = new URL('lessons.js', root);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== output) throw new Error('lessons.js needs regeneration');
} else await writeFile(target, output);
console.log(`${chapters.length} lessons; ${Object.values(lessons).reduce((n,l) => n+l.words,0)} words; complete coverage.`);
